import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import PromptDetailPage from "@/app/prompts/[id]/page";
import {
  freeVideoEntry,
  paidEntry,
  stubCatalogFetch,
  stubIntersectionObserver,
  stubMatchMedia,
  stubMediaElement,
} from "./helpers";

// The page reads its id from next/navigation's useParams; drive it per test.
const currentParams = { id: "test-prompt" };
vi.mock("next/navigation", () => ({
  useParams: () => currentParams,
}));

beforeEach(() => {
  stubMediaElement();
  stubIntersectionObserver();
  stubMatchMedia(true);
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("prompt detail", () => {
  it("renders a not-found state for an unknown id", async () => {
    currentParams.id = "does-not-exist";
    stubCatalogFetch([freeVideoEntry]);
    render(<PromptDetailPage />);

    expect(
      await screen.findByRole("heading", { name: "Prompt not found" }),
    ).toBeTruthy();
    // The dead end offers a way back to the gallery.
    expect(screen.getByRole("link", { name: "Browse the gallery" })).toBeTruthy();
  });

  it("renders the entry with attribution and copy control for a free prompt", async () => {
    currentParams.id = freeVideoEntry.id;
    stubCatalogFetch([freeVideoEntry]);
    render(<PromptDetailPage />);

    expect(
      await screen.findByRole("heading", { name: freeVideoEntry.title }),
    ).toBeTruthy();
    expect(screen.getByText(freeVideoEntry.attribution.note)).toBeTruthy();
    expect(
      screen.getByRole("button", {
        name: `Copy the full prompt text of ${freeVideoEntry.title}`,
      }),
    ).toBeTruthy();
  });

  it("renders price, unlock control, and the output claim for a paid prompt", async () => {
    currentParams.id = paidEntry.id;
    stubCatalogFetch([paidEntry]);
    render(<PromptDetailPage />);

    expect(await screen.findByRole("heading", { name: paidEntry.title })).toBeTruthy();
    expect(screen.getByLabelText("Price: $0.50 in USDC")).toBeTruthy();
    expect(
      screen.getByRole("button", {
        name: `Unlock ${paidEntry.title} for $0.50 in USDC`,
      }),
    ).toBeTruthy();
    expect(screen.getByText(/generated by running this\s+exact prompt/)).toBeTruthy();
    // The signature-not-transaction story is visible before any wallet UI (U6).
    expect(screen.getByText(/not a transaction/)).toBeTruthy();
  });

  it("renders an error state with a way back when the API is unreachable", async () => {
    currentParams.id = freeVideoEntry.id;
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new TypeError("network down")));
    render(<PromptDetailPage />);

    const alert = await screen.findByRole("alert");
    // Scoped: the page header carries its own "Back to gallery" link too.
    expect(within(alert).getByRole("link", { name: "Back to gallery" })).toBeTruthy();
  });
});
